### ISSUE TITLE
Can not access /index.php?r=v1/posts, get 401 Unauthorized

### ISSUE THREAD

**Issue by elim051** [githubjeka/yii2-rest#11]
![unnamed qq screenshot20151202121244](https://cloud.githubusercontent.com/assets/6869709/11522108/a138970c-98ee-11e5-92cb-d7a4a98cd846.png)

All the pages are 401 except login. Need I change something?
How to access the page? Thanks!!!!

**Comment by githubjeka** [comment]
https://github.com/githubjeka/yii2-rest/issues/6#issuecomment-101134848

**Comment by elim051** [comment]
Thank you very much!
