### ISSUE TITLE
Exception 'yii\base\InvalidRouteException'

### ISSUE THREAD

**Issue by githubjeka** [githubjeka/yii2-rest#2]
Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "site/error".
Associated with aliases.

**Comment by horizons2** [comment]
you have used the wrong alias in  yii2-rest/common/config/bootstrap.php
Yii::setAlias('frontend', dirname(dirname(__DIR__)) . '/frontend');
must be 
Yii::setAlias('backend', dirname(dirname(__DIR__)) . '/backend');

or you use the aliases.php file which you haven't used at all ;)
