### ISSUE TITLE
Response format

### ISSUE THREAD

**Issue by Lesac76** [githubjeka/yii2-rest#3]
yii2-rest/rest/config/bootstrap.php
Content of this file: <?php

That prevents the response format to be correct json if username and password is left blank, you get:
```json
<?php
[{"field":"username","message":"Username cannot be blank."},{"field":"password","message":"Password cannot be blank."}]
```

With blank bootstrap.php you get correct json format:
```json
[{"field":"username","message":"Username cannot be blank."},{"field":"password","message":"Password cannot be blank."}]
```

**Comment by githubjeka** [comment]
Hmm.... Now I get (with `<?php`)
```json
[{"field":"username","message":"Username cannot be blank."},{"field":"password","message":"Password cannot be blank."}]
```

Perhaps you stumbled on something else.
