### ISSUE TITLE
About rate limit

### ISSUE THREAD

**Issue by lichunqiang** [githubjeka/yii2-rest#4]
Hi,
https://github.com/githubjeka/yii2-rest/blob/master/rest/versions/v1/models/User.php#L28-L34

The cache key will be the same to every one, Maybe can join with the user id to identity for different user?

**Comment by githubjeka** [comment]
Cache key may be any. You can use authenticated user identity information instead `$request->getPathInfo() . $request->getMethod()`. It can be retrieved via `Yii::$app->user->identity.`

**Comment by lichunqiang** [comment]
Understand, thanks!
