### ISSUE TITLE
cannot access to rest api

### ISSUE THREAD

**Issue by alexwang2013** [githubjeka/yii2-rest#7]
when i visit the backend using the following url, it works fine.
http://localhost/yii2api/rest-yii2/backend/web/index.php?r=site%2Flogin

But when i visit the rest api using the following url:
http://localhost/yii2api/rest-yii2/rest/web/index.php?r=v1/posts

it gave me an error:
{"name":"Not Found","message":"Page not found.","code":0,"status":404,"type":"yii\\web\\NotFoundHttpException"}

where should i configure if i want to use rest api?

**Comment by githubjeka** [comment]
You should configurate `urlManager`

https://github.com/githubjeka/yii2-rest/blob/master/rest/config/main.php#L52

**Comment by alexwang2013** [comment]
thanks for your quick reply. 
I used the urlManager the same as that configuration. 

If I didnot have token, it should response unauthorized, not "not found". Right?

**Comment by githubjeka** [comment]
https://yii2-rest-githubjeka.c9.io/rest/web/v1/posts

**Comment by alexwang2013** [comment]
Hi githubjeka,
I found the problem here.
I used symbolic link to hosted the folder, and I used the following to rewrite the url. but it failed for Apache 4.7.
<Directroy /home/user/yii2api/rest-yii2/rest/web>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
                RewriteEngine on
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteRule (.*) index.php [L]
 </Directory>

then I changed to Location, as the following:
<Location /yii2api/rest-yii2/rest/web>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
                RewriteEngine on
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteRule (.*) index.php [L]
</Location>

now when i access by the url http://localhost/yii2api/rest-yii2/rest/web/v1/posts
it works fine.

though it also shows <name>Unauthorized</name>
but it worked for rest api.

Thank you.
yii2-rest and angluar is very excellent.
