### ISSUE TITLE
I'm not able to access rest url?

### ISSUE THREAD

**Issue by rijine** [githubjeka/yii2-rest#9]
![image](https://cloud.githubusercontent.com/assets/1145401/9382932/813ab3d2-4762-11e5-8d48-b449f7b09c02.png)
&
![image](https://cloud.githubusercontent.com/assets/1145401/9382944/9a2334d2-4762-11e5-9265-463df3f248a4.png)

**Comment by rijine** [comment]
![image](https://cloud.githubusercontent.com/assets/1145401/9382964/b9107846-4762-11e5-9a36-78ccc80e28ea.png)
@githubjeka will u please help me?. I followed steps you mentioned in home page!

**Comment by githubjeka** [comment]
https://github.com/githubjeka/yii2-rest/issues/8

 Try again. Server reloaded.

**Comment by githubjeka** [comment]
Ahhh localhost.... :)

https://github.com/githubjeka/yii2-rest/blob/master/server.md

**Comment by rijine** [comment]
@githubjeka what i will do with this? 
you mean creating .htaccess file under htdocs/yii2-rest/  ?

**Comment by githubjeka** [comment]
in htdocs/yii2-rest/rest/web/

**Comment by rijine** [comment]
@githubjeka thank you for you reply....i will try this.
